CREATE TABLE `c01_DataStore`.`Exclusions` (
    `PoolId` TEXT NULL DEFAULT NULL,
    `SubjectId` TEXT NULL DEFAULT NULL,
    `OS` TEXT NULL DEFAULT NULL,
    `Browser` TEXT NULL DEFAULT NULL,
    `ScreenWidth` INT UNSIGNED NULL DEFAULT NULL,
    `ScreenHeight` INT UNSIGNED NULL DEFAULT NULL,
    `DateTime_Exclude` DATETIME NULL DEFAULT NULL
) ENGINE = InnoDB;