CREATE TABLE `c01_DataStore`.`Relandings` (
    `PoolId` TEXT NULL DEFAULT NULL,
    `SubjectId` TEXT NULL DEFAULT NULL,
    `State` INT NULL DEFAULT NULL,
    `DateTime_Reland` DATETIME NULL DEFAULT NULL
) ENGINE = InnoDB