CREATE TABLE `c01_DataStore`.`Unfocuses` (
    `SubjectId` TEXT NULL DEFAULT NULL,
    `State` INT NULL DEFAULT NULL,
    `Href` TEXT NULL DEFAULT NULL,
    `DateTime_Unfocus` DATETIME NULL DEFAULT NULL
) ENGINE = InnoDB;